name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or your preferred version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Set version from Git tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Setting version to $TAG_VERSION"
          npm version "$TAG_VERSION"

      - name: Push version bump commit
        run: git push origin HEAD

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  