name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to push commits
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for pushing commits

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Detect branch for tag
        id: branch_check
        run: |
          BRANCH=$(git name-rev --name-only $GITHUB_SHA)
          echo "Detected branch: $BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Set version from Git tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v} 
          echo "Setting version to $TAG_VERSION"
          npm version "$TAG_VERSION" --no-git-tag-version

      - name: Commit and push version bump
        if: steps.branch_check.outputs.branch == 'main'
        run: |
          git checkout main
          git pull origin main
          git add package.json
          git commit -m "chore: bump version to v${GITHUB_REF#refs/tags/v}"
          git push origin main

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
